### ISSUE TITLE
FPS is not reaching to the demanding

### ISSUE THREAD

**Issue by qtw1998** [rt-net/jetson_nano_csi_cam_ros#13]
# 現状の問題点

Thanks, bro! I wanna ask if there is anything possible to do dealing with the FPS is far lower than if no push to one topic
like:
```python
import cv2
 
 
def gstreamer_pipeline(
    capture_width=1280,
    capture_height=720,
    display_width=1280,
    display_height=720,
    framerate=60,
    flip_method=0,
):
    return (
        "nvarguscamerasrc ! "
        "video/x-raw(memory:NVMM), "
        "width=(int)%d, height=(int)%d, "
        "format=(string)NV12, framerate=(fraction)%d/1 ! "
        "nvvidconv flip-method=%d ! "
        "video/x-raw, width=(int)%d, height=(int)%d, format=(string)BGRx ! "
        "videoconvert ! "
        "video/x-raw, format=(string)BGR ! appsink"
        % (
            capture_width,
            capture_height,
            framerate,
            flip_method,
            display_width,
            display_height,
        )
    )
 
 
def show_camera():
    cap = cv2.VideoCapture(gstreamer_pipeline(flip_method=0), cv2.CAP_GSTREAMER)
 
    while cap.isOpened():
        flag, img = cap.read()
        cv2.imshow("CSI Camera", img)
        kk = cv2.waitKey(1)
 
        # do other things
 
        if kk == ord('q'):  
            break
 
    cap.release()
    cv2.destroyAllWindows()
    
 
if __name__ == "__main__":
    show_camera()
```
☝could run 1080P at 60FPS, but if listen to rostopic bw when using this repo,  I only get a 10 FPS data stream(locally on the Jetson Nano, I feel no relation with the WIFI condition...)
# 改善案

So I wanna learn from you if there are some done or config the wrong places.
# 代替案

# その他

Finally, Thx for your contribution!!

**Comment by Tiryoh** [comment]
Hi, @qtw1998. Thanks for your feedback.

>  I only get a 10 FPS data stream(locally on the Jetson Nano, I feel no relation with the WIFI condition...)

In my case, it was 26 FPS, but the target FPS is 60, so I can say that I was able to reproduce the problem.

```
roslaunch jetson_nano_csi_cam jetson_csi_cam.launch width:=1080 height:=720 fps:=60
```

![Screenshot from 2021-08-12 01-57-37](https://user-images.githubusercontent.com/3256629/129071274-31a19bf5-ea14-4569-9a2f-d909f816b2ee.png)

The CPU usage of the `gscam` process that is launched by `jetson_csi_cam.launch` is at 100%. It may be that the specs are a bit too demanding for the Jetson Nano to convert camera image to ROS topic format in 60 FPS.
The implementation of [dusty-nv/jetbot_ros](https://github.com/dusty-nv/jetbot_ros) and [dusty-nv/ros_deep_learning](https://github.com/dusty-nv/ros_deep_learning) is designed to use the GPU.

FYI
I'm also preparing jetson_nano_cuda_csi_cam_ros which is the GPU implementation version of jetson_nano_csi_cam_ros and I'll share it when it's released.

![Screenshot from 2021-08-12 09-25-06](https://user-images.githubusercontent.com/3256629/129120133-f69c9c16-91c3-40ca-a683-fd9b33ec5fc3.png)

**Comment by Tiryoh** [comment]
Hi @qtw1998,

Sorry it took me so long to get back to you!
I've finally released a version of the ROS package that uses CUDA. Please check this out!

https://github.com/rt-net/jetson_nano_cuda_csi_cam_ros

Happy holidays!

**Comment by Tiryoh** [comment]
Here is some information for those who found this Issue.
The CPU load of the `gscam` process seems to be much less on JetPack 4.5.1. The two CSI camera image topics were successfully received at 60 Hz.
It may be that JetPack 4.4 has similar improvements, but I have not checked.
[The information in this Issue](https://github.com/rt-net/jetson_nano_csi_cam_ros/issues/13#issuecomment-897254530) was confirmed with JetPack 4.3.
![2022-02-15-152416](https://user-images.githubusercontent.com/3256629/154005454-2901c4c9-d166-4be0-99e5-7bb1a089da93.jpg)
